stages:
        - build

build:
        stage: build
        tags:
                - CS425
        image: golang:1.9.2
        before_script:
        script:
                # Compile and name the binary as `server.bin` and `client.bin`
                - go build -o server.bin ./server && go build -o client.bin ./client
                # Execute the binary
                - ./server.bin
